const PLANOS_PAGOS={basic:{nome:'Básico',descricao:'Para organizar o negócio',periodos:{31:{preco:10},61:{preco:18},91:{preco:25}}},pro:{nome:'Pró',descricao:'Tudo liberado e ilimitado',periodos:{31:{preco:20},61:{preco:35},91:{preco:50}}}};
function infoLicencaLocal(){try{return JSON.parse(localStorage.getItem('anotaaiLicenseInfo')||'{}')||{};}catch{return{};}}
function planoAtual(){const i=infoLicencaLocal(),raw=i.plan==='premium'?'pro':(i.plan||'free'),e=i.premiumExpiresAt?new Date(i.premiumExpiresAt):null;return raw!=='free'&&e&&e<new Date()?'free':(['free','basic','pro'].includes(raw)?raw:'free');}
function planoBasico(){return planoAtual()==='basic';}function planoPro(){return planoAtual()==='pro';}function planoPremium(){return planoPro();}
function nomePlano(){return ({free:'Free',basic:'Básico',pro:'Pró'})[planoAtual()];}
function validadePremium(){const i=infoLicencaLocal();if(planoAtual()==='free')return'';return i.premiumExpiresAt?`até ${new Date(i.premiumExpiresAt).toLocaleDateString('pt-BR')}`:'';}
function limiteClientesPlano(){return planoPro()?Infinity:planoBasico()?50:10;}function limiteProdutosPlano(){return planoPro()?Infinity:planoBasico()?10:5;}
function verificarAvisoVencimentoPremium(){const i=infoLicencaLocal();if(planoAtual()==='free'||!i.premiumExpiresAt)return;const partes=String(i.premiumExpiresAt).slice(0,10).split('-').map(Number);if(partes.length!==3||partes.some(x=>!Number.isFinite(x)))return;const hoje=new Date(),inicioHoje=new Date(hoje.getFullYear(),hoje.getMonth(),hoje.getDate()),vencimento=new Date(partes[0],partes[1]-1,partes[2]),dias=Math.round((vencimento-inicioHoje)/86400000),chave=`plano-${i.plan}-${String(i.premiumExpiresAt).slice(0,10)}`;if(dias===1&&localStorage.getItem('anotaaiAvisoVencimentoPremium')!==chave){localStorage.setItem('anotaaiAvisoVencimentoPremium',chave);setTimeout(()=>alertaAviso(`! Atenção: falta 1 dia para vencer seu plano ${nomePlano()}.`,'Plano próximo do vencimento'),350);}}
function planApiConfigurada(){const u=String(window.ANOTAAI_PLAN_API||'');return/^https:\/\//i.test(u)&&!u.includes('SEU-DOMINIO');}
async function chamarApiPlano(action,extra={}){if(!planApiConfigurada())throw new Error('Configure a API dos planos.');const r=await fetch(window.ANOTAAI_PLAN_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,license:localStorage.getItem('anotaaiLicenseCode')||'',deviceId:obterIdDispositivo(),...extra})});let j;try{j=await r.json();}catch{throw new Error('Resposta inválida do servidor.');}if(!r.ok||!j.ok)throw new Error(j.error||'Não foi possível consultar o plano.');if(j.licenseInfo)localStorage.setItem('anotaaiLicenseInfo',JSON.stringify({...infoLicencaLocal(),...j.licenseInfo}));return j;}
async function atualizarPlano(s=true){try{return await chamarApiPlano('status');}catch(e){if(!s)alert(e.message);return null;}}
function abrirOfertaPremium(){const m=document.createElement('div');m.id='modalPremium';m.className='modal-backdrop';m.innerHTML=`<div class="modal-box premium-modal"><button class="modal-close premium-close" onclick="fecharModal('modalPremium')">×</button><div class="premium-icon">★</div><h2>Escolha seu plano</h2><p class="muted">Selecione o plano ideal para o seu negócio.</p><div class="subscription-tiers"><button onclick="escolherPlanoAssinatura('basic')"><b>Básico</b><strong>A partir de ${money(10)}</strong><span>50 clientes · 10 produtos · 5 relatórios</span></button><button class="pro" onclick="escolherPlanoAssinatura('pro')"><b>Pró</b><strong>A partir de ${money(20)}</strong><span>Tudo liberado e ilimitado</span></button></div></div>`;document.body.appendChild(m);}
function escolherPlanoAssinatura(tipo){const p=PLANOS_PAGOS[tipo],box=document.querySelector('#modalPremium .premium-modal');if(!p||!box)return;box.innerHTML=`<button class="modal-close premium-close" onclick="fecharModal('modalPremium')">×</button><button class="subscription-back" onclick="fecharModal('modalPremium');abrirOfertaPremium()">‹ Planos</button><div class="premium-icon">${tipo==='pro'?'★':'✓'}</div><h2>Plano ${p.nome}</h2><p class="muted">${p.descricao}. Por quantos dias deseja contratar?</p><div class="premium-plans">${Object.entries(p.periodos).map(([dias,o],i)=>`<label class="premium-plan ${i===0?'selected':''}"><input type="radio" name="premiumPlan" value="${tipo}_${dias}" ${i===0?'checked':''} onchange="selecionarPlanoPremium(this)"><span><b>${dias} dias</b><small>${dias==='31'?'1 mês':dias==='61'?'2 meses':'3 meses'}</small></span><strong>${money(o.preco)}</strong></label>`).join('')}</div><div class="coupon-box"><label>Cupom de desconto</label><div><input id="premiumCoupon" placeholder="Digite o código" autocapitalize="characters"><button class="btn secondary" onclick="aplicarCupomPremium(this)">Aplicar</button></div><p id="couponStatus" class="muted"></p></div><div class="premium-total"><span>Total</span><strong id="premiumTotal">${money(p.periodos[31].preco)}</strong></div><button class="btn premium-button" onclick="iniciarCheckoutPremium(this)">Continuar para o pagamento</button><p class="muted premium-note">O plano é ativado automaticamente após a aprovação.</p>`;}
function selecionarPlanoPremium(input){document.querySelectorAll('.premium-plan').forEach(x=>x.classList.toggle('selected',x.contains(input)));const[tipo,dias]=input.value.split('_');premiumCoupon.value='';couponStatus.textContent='';premiumTotal.textContent=money(PLANOS_PAGOS[tipo].periodos[dias].preco);}
function planoPremiumSelecionado(){return document.querySelector('input[name="premiumPlan"]:checked')?.value||'basic_31';}
async function aplicarCupomPremium(botao){const coupon=premiumCoupon.value.trim().toUpperCase();if(!coupon)return alertaAviso('Digite o cupom antes de aplicar.','Cupom');try{botao.disabled=true;couponStatus.textContent='Validando...';const r=await chamarApiPlano('validate_coupon',{planKey:planoPremiumSelecionado(),coupon});premiumTotal.textContent=money(r.finalPrice);couponStatus.textContent=r.discount>0?`Cupom aplicado: ${money(r.discount)} de desconto!`:'Cupom válido.';couponStatus.className='coupon-success';}catch(e){couponStatus.textContent=e.message;couponStatus.className='coupon-error';}finally{botao.disabled=false;}}
async function iniciarCheckoutPremium(botao){try{botao.disabled=true;botao.textContent='Preparando pagamento...';const r=await chamarApiPlano('checkout',{planKey:planoPremiumSelecionado(),coupon:premiumCoupon.value.trim().toUpperCase()});if(r.activated){fecharModal('modalPremium');alertaSucesso('✅ Cupom aplicado. Plano ativado com sucesso!');home();return;}if(!r.checkoutUrl)throw new Error('Link de pagamento não recebido.');location.href=r.checkoutUrl;}catch(e){alertaErro(`❌ Pagamento não iniciado. ${e.message}`);botao.disabled=false;botao.textContent='Continuar para o pagamento';}}
async function consumirRelatorioFree(){if(planoPro())return true;try{await chamarApiPlano('consume_report');return true;}catch(e){alertaPremium(e.message);return false;}}
function exigirPro(r){if(planoPro())return true;alertaPremium(`${r||'Este recurso'} está disponível no plano Pró.`);return false;}
function exigirPremium(r){return exigirPro(r);}
async function verificarRetornoPremium(){const p=new URLSearchParams(location.search);if(!p.has('premium'))return;history.replaceState({},'',location.pathname+location.hash);if(p.get('premium')==='sucesso'){const r=await atualizarPlano(true);setTimeout(()=>r?.licenseInfo?.plan!=='free'?alertaSucesso(`✅ Plano ${nomePlano()} ativado com sucesso!`):alertaAviso('Pagamento recebido. A ativação pode levar alguns instantes.','Pagamento recebido'),400);}else if(p.get('premium')==='pendente')setTimeout(()=>alertaAviso('O plano será ativado após a confirmação.','Pagamento pendente'),400);else if(p.get('premium')==='cancelado')setTimeout(()=>alertaErro('❌ Pagamento não concluído. Você pode tentar novamente quando quiser.'),400);}
